---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jump-host-config
  namespace: dkp-over-dvp
data:
  ssh-pub-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID60hpJqw1U58nkE1ZyG5utjr3hloBZrvR5MrSMMHArs cloud"
