---
apiVersion: v1
kind: Service
metadata:
  name: jump-host
  namespace: dkp-over-dvp
spec:
  type: NodePort
  selector:
    app: jump-host
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
